In [56]:
import numpy as np
import pandas as pd
from numpy import linalg

In [26]:
# Задание 1
N = 10

x = np.arange(N-1,-1,-1)
print(x)
print(type(x))

[9 8 7 6 5 4 3 2 1 0]
<class 'numpy.ndarray'>


In [27]:
# Задание 2
x = np.diag(np.arange(N-1,-1,-1), k=0)
print(x)

matrix_sum = 0

for i in range(N):
    matrix_sum += x[i][i]
    
print(matrix_sum)

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
45


In [36]:
# Задание 3
data = pd.read_csv("ratings.csv")

data[ data.rating == 5 ].groupby('movieId').count().sort_values('movieId', ascending=False).head()

userId  rating  timestamp
movieId                           
131050        1       1          1
130996        1       1          1
130978        1       1          1
130970        1       1          1
130644        1       1          1

In [55]:
# Задание 4
data = pd.read_csv('power.csv')

filtered_countries = data[ ((data['country'] == 'Latvia') | (data['country'] == 'Lithuania') | (data['country'] == 'Estonia')) &
                           ((data['category'] == 4) | (data['category'] == 12) | (data['category'] == 21)) &
                           ((data['year'] >= 2005) & (data['year'] <= 2010)) & 
                           (data['quantity'] >= 0)]

filtered_countries['quantity'].sum()

240580.0

In [57]:
# Задание 5
a = np.array( [ [2, 4, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

linalg.solve(a, b)

array([-5.76923077,  5.92307692, -8.15384615])